export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';

export const FETCH_ADS_COUNT_REQUEST = 'FETCH_ADS_COUNT_REQUEST';
export const FETCH_ADS_COUNT_SUCCESS = 'FETCH_ADS_COUNT_SUCCESS';
export const FETCH_ADS_COUNT_FAILURE = 'FETCH_ADS_COUNT_FAILURE';

export const ADS_PAGE_INCREMENT = 'ADS_PAGE_INCREMENT';
export const ADS_PAGE_DECREASE = 'ADS_PAGE_DECREASE';

export const FETCH_LOCALITIES_REQUEST = 'FETCH_LOCALITIES_REQUEST';
export const FETCH_LOCALITIES_SUCCESS = 'FETCH_LOCALITIES_SUCCESS';
export const FETCH_LOCALITIES_FAILURE = 'FETCH_LOCALITIES_FAILURE';

export const FETCH_REGIONS_REQUEST = 'FETCH_REGIONS_REQUEST';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_FAILURE = 'FETCH_REGIONS_FAILURE';

export const SEARCH_FILTER_CHANGE = 'SEARCH_FILTER_CHANGE';

export const AD_POPUP_SHOW_STATUS_CHANGE = 'AD_POPUP_SHOW_STATUS_CHANGE';
export const FETCH_AD_POPUP_REQUEST = 'FETCH_AD_POPUP_REQUEST';
export const FETCH_AD_POPUP_SUCCESS = 'FETCH_AD_POPUP_SUCCESS';
export const FETCH_AD_POPUP_FAILURE = 'FETCH_AD_POPUP_FAILURE';
export const FETCH_AD_POPUP_PICS_REQUEST = 'FETCH_AD_POPUP_PICS_REQUEST';
export const FETCH_AD_POPUP_PICS_SUCCESS = 'FETCH_AD_POPUP_PICS_SUCCESS';
export const FETCH_AD_POPUP_PICS_FAILURE = 'FETCH_AD_POPUP_PICS_FAILURE';
